const excludedTags = ["(Les Grandes Personnes)",
"2010's",
"20ème siècle",
"21ème siècle",
"à partir de 3 ans",
"à partir de 4 ans",
"album",
"album illustré",
"Albums",
"albums jeunesse",
"anglais",
"années 2000",
"bébés",
"bébés lecteurs",
"conte de randonnée",
"contes",
"contes détournés",
"Collection Trapèze chez Albin Michel",
"cycle 3",
"Des maisons d’édition",
"Des thèmes",
"Des types de livres",
"dessins",
"Divers",
"documentaire jeunesse",
"Documentaires",
"Écoles maternelles",
"écrivain femme",
"écrivain homme",
"Édition spécialisée - Format poche",
"Édition spécialisée - Livres animés",
"éditions école des loisirs",
"égalité",
"enfance",
"enfants",
"états-unis",
"Fiction",
"Fiction - Fiction en langue française contemporaine",
"france",
"Genévrier",
"histoire",
"histoire naturelle",
"Histoires en images",
"Histoires en images - La nature",
"illustrations",
"illustré par l'auteur",
"jeunesse",
"jeux",
"légendes",
"littérature",
"littérature allemande",
"littérature américaine",
"littérature anglaise",
"littérature belge",
"littérature française",
"littérature francophone",
"littérature jeunesse",
"littérature pour adolescents",
"littérature pour enfants",
"livre cartonne",
"magique",
"manipulation",
"mémoire",
"oeuvres de jeunesse",
"peintre",
"petite enfance",
"photos",
"poèmes",
"poésie",
"poetique",
"randonnées",
"récits",
"recueil",
"roman",
"Romans et nouvelles",
"Romans et nouvelles - Romans d'aventures",
"romans policiers et polars",
"selection joie par les livres",
"tout-petits",
"traditions"];
export { excludedTags }
